name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install rustfmt
      run: rustup component add rustfmt

    - name: Check formatting
      id: fmt_check
      run: cargo fmt --all -- --check

    - name: Fix formatting (if needed)
      if: failure()
      run: |
        cargo fmt --all
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Apply rustfmt fixes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
